apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearchh
spec:
  selector:
    matchLabels:
      component: elasticsearchh
  template:
    metadata:
      labels:
        component: elasticsearchh
    spec:
      containers:
      - name: elasticsearchh
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        env:
          - name: discovery.type
            value: single-node
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile1
 

---


apiVersion: v1
kind: Service
metadata:
 name: elasticsearchh
 labels:
  service: elasticsearchh
spec:
 type: LoadBalancer
 selector:
  component: elasticsearchh
 ports:
  - port: 9200
    targetPort: 9200
